pipeline {
    agent any

    tools {
        maven 'Maven'
        jdk 'JDK11'
    }

    stages {

        stage('Clone') {
            steps {
                git 'https://github.com/Vipvishnu12/Demo-jenkins.git'
            }
        }

        stage('Build') {
            steps {
                bat 'mvnd clean package'
            }
        }

        stage('Run') {
            steps {
                bat 'java -cp target/jenkins-demo-1.0.jar Main'
            }
        }
    }
}